'	<form action="http://localhost/cgi-bin/upload" enctype="multipart/form-data" method="post">' + LF +
'		<input type="file" name="file1edit" required/><br />' + LF +
'		<input type="file" name="file2edit" required/><br />' + LF +
'		<input type="text" name="field1edit" required/><br />' + LF +
'		<input type="text" name="field2edit" required/><br />' + LF +
'		<input type="submit"/>' + LF +
'	</form>'
